# Generated by Django 2.2.4 on 2019-08-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlAdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('timeshift', models.PositiveIntegerField(default=0, verbose_name='Time shift (in secs)')),
                ('success', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('h1', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('charset', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
