# Generated by Django 2.2.4 on 2019-08-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190830_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlAdminModel',
            new_name='Post',
        ),
    ]
