# Generated by Django 2.2.4 on 2019-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190830_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeshift',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(),
        ),
    ]
