# Generated by Django 2.2.4 on 2019-09-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190902_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='charset',
        ),
        migrations.AddField(
            model_name='post',
            name='unicode',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='h1',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
