# Generated by Django 2.2.4 on 2019-09-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190903_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='unicode',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
