# Generated by Django 2.2.4 on 2019-09-04 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190904_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
