# Generated by Django 2.2.4 on 2019-09-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190904_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(blank=True, default='2019.09.04 12:40:19', null=True),
        ),
    ]
