# Generated by Django 2.2.4 on 2019-09-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190904_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(blank=True, default='2019-09-04 12:44:18', null=True),
        ),
    ]
