# Generated by Django 2.2.4 on 2019-09-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190904_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(blank=True, default='2019-09-04 13:09:51', null=True),
        ),
    ]
