# Generated by Django 2.2.4 on 2019-09-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190904_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(blank=True, default='2019-09-04 13:18:09', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='unicode',
            field=models.CharField(blank=True, default='UTF-8', max_length=16, null=True),
        ),
    ]
