# Generated by Django 2.2.4 on 2019-09-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190904_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='unicode',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
