# Generated by Django 2.2.4 on 2019-09-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190904_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='unicode',
            new_name='encode',
        ),
    ]
